### ISSUE TITLE
Add son-cli schema validator to tng-sdk-validation

### ISSUE THREAD

**Issue by antonroman** [sonata-nfv/tng-sdk-validation#17]
In order to be able to check the syntax of services, functions and packages we need to re-use and adapt the schema validation tool from son-clit tng-sdk-validation. 
The schema validation tool must be imported as a sub-package so that it can be imported by other modules to be used independently.

**Comment by antonroman** [comment]
@mpeuster does this issue sound good to you? I don't know if this already being used in any other Tango tool. Any advice is welcome, thanks!

**Comment by mpeuster** [comment]
Sounds fine for me. No other tool implements the validation yet. Right now, I do only very basic checks in the packager.

I followed a similar approach for the packaging tool. I basically copied the old packager code from son-cli and modified it to work independently of the other son-cli tools. Then I started to extend it for 5GTANGO. I think it is important that all our small SDK tools can be used independently from each other. Having all in son-cli was a mistake.

However, would be cool if I could later import the validator into `tng-sdk-package` and use it to validate stuff. As a optional operation of course, so that people could use the packager without it, if they want, e.g., `--validate` in the packager's CLI would trigger the import and use of tng-validate if it is available on the developers system. 

Does this fit to your view?

**Comment by jbonnet** [comment]
I stand by you, @mpeuster & @antonroman 

Can we make this validator a python library, something lighter than a container that can be imported into other (python-based) chunks of code? Then, a container-based/HTTP REST interface version would enable it to be re-used in other techstacks as well...

**Comment by mpeuster** [comment]
@jbonnet full ack! In fact I designed the packager like this to maximize its usefulness:

* can be used as Python lib
* can be used as CLI tool
* can be used as REST service

Would be super if the validator (and best all our SDK tools) could do the same.

**Comment by antonroman** [comment]
Thanks for your feedback @mpeuster and @jbonnet 
Sure, we are following the same structure of the tng-sdk-package so that the tng-sdk-validation will be a library which can also be used via CLI and REST API. It will internally use  tng-sdk-project to manage workspaces.
 The schema validation code will be a subpackage which could also be imported individually if any other module needs to verify the syntax of a descriptor.
