### ISSUE TITLE
Use schema file included in the descriptor instead of default one

### ISSUE THREAD

**Issue by antonroman** [sonata-nfv/tng-sdk-validation#30]
In 5gTANGO, the descriptor file includes a `descriptor_schema` field which contains the URL of the schema to be used for the syntax validation instead of the one by default:

```
---
descriptor_schema: "https://raw.githubusercontent.com/sonata-nfv/tng-schema/master/service-descriptor/nsd-schema.yml"

vendor: "eu.sonata-nfv.service-descriptor"
name: "simplest-example"
version: "0.2"
```

**Comment by danifernandezcalv** [comment]
In 5gTANGO the descriptor files included a descriptor_schema field which contains the URL of the schema to be used for the syntax validation, right now validator use default schema included in tng-schema. In the future we should use the schema defined in the descriptor instead of the default one. In this case, if the schema defined can't be downloaded (server down, offline mode....) what we should do? (use the default schema of the tng-schema, exit validation indicating the error..)

@mpeuster @StefanUPB this is not an urgent issue, so please answer it when you have time. We just need to solved it to keep working in validator for the 2yreview.

Thanks.

**Comment by StefanUPB** [comment]
What default schema do you currently use? 

I would suggest to copy the current [NSD ](https://github.com/sonata-nfv/tng-schema/blob/master/service-descriptor/nsd-schema.yml) and [VNFD ](https://github.com/sonata-nfv/tng-schema/blob/master/function-descriptor/vnfd-schema.yml) schema from tng-schma and include it in your repo.
If the referenced schema in the `descriptor_schema` field cannot be fetched, I would show a warning and fall back to the downloaded schema. This would allow offline validation. At the moment we don't have frequent schema changes anyways.

What do you think?
